services:

  flat-price-api:
    build: .
    container_name: flat-price-api
    working_dir: /root/MLOps/Projekt_1
    volumes:
      - .:/root/MLOps/Projekt_1
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=0.0.0.0:9090"
    ports:
      - "127.0.0.1:9090:9090"
    depends_on:
      - flat-price-api
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

  airflow:
    image: apache/airflow:2.10.5-python3.11
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "flat-price-airflow-secret"
    volumes:
      - airflow-home:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - flat-price-api
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com
      --password admin || true &&
      airflow scheduler &
      exec airflow webserver --port 8080
      "
    restart: unless-stopped

volumes:
  grafana-storage:
  airflow-home:
